In [8]:
import pandas as pd
movies = pd.read_csv('./data/movies.csv', sep=',')
movies = movies[:100]

In [27]:
movies.head(5)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [12]:
movies["overview"][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [ ]:
import re
from sklearn.feature_extraction.text import TfidfVectorizer

def custom_tokenizer(text):
    """
    Tokenizes the input text into a list of words, excluding any words that contain digits.

    Args:
        text (str): The input text to be tokenized.

    Returns:
        list: A list of tokens (words) from the input text, excluding any words that contain digits.
    """
    tokens = re.findall(r'\b\w+\b', text)
    return [token for token in tokens if not any(char.isdigit() for char in token)]

vectorizer = TfidfVectorizer(stop_words='english', tokenizer=custom_tokenizer)
X_train = vectorizer.fit_transform(movies["overview"])
feature_names = vectorizer.get_feature_names_out()

c:\Users\fernoWin11\Documents\pythonProjects\movieRecommendation\.venv\lib\site-packages\sklearn\feature_extraction\text.py:521: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

In [18]:
pd.DataFrame(X_train.toarray(), columns=feature_names).head(6)

,abandoned,abducted,aboard,absence,abuse,accidentally,acclimated,accomplished,accuser,act,...,x,xavier,year,years,york,young,younger,youth,zombies,zone
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.098272,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0

In [24]:
from sklearn.metrics.pairwise import cosine_similarity
similarity_matrix0 = cosine_similarity(X_train, X_train)
similarity_matrix0[:5,:5]

array([[1.        , 0.        , 0.        , 0.02662793, 0.        ],
       [0.        , 1.        , 0.        , 0.        , 0.02990671],
       [0.        , 0.        , 1.        , 0.01199238, 0.01035416],
       [0.02662793, 0.        , 0.01199238, 1.        , 0.03277308],
       [0.        , 0.02990671, 0.01035416, 0.03277308, 1.        ]])

In [26]:
from sklearn.metrics.pairwise import linear_kernel
similarity_matrix1 = linear_kernel(X_train, X_train)
similarity_matrix1[:5,:5]

array([[1.        , 0.        , 0.        , 0.02662793, 0.        ],
       [0.        , 1.        , 0.        , 0.        , 0.02990671],
       [0.        , 0.        , 1.        , 0.01199238, 0.01035416],
       [0.02662793, 0.        , 0.01199238, 1.        , 0.03277308],
       [0.        , 0.02990671, 0.01035416, 0.03277308, 1.        ]])

In [44]:
movie_name = "Spectre"
movie_idx = movies[movies["title"]==movie_name].index[0]
print(f"Movie index for '{movie_name}': {movie_idx}")

Movie index for 'Spectre': 2

In [48]:
similarity_scores = list(enumerate(similarity_matrix0[movie_idx]))
similarity_scores_sorted = sorted(similarity_scores, key=lambda x: x[1], reverse=True)
similarity_scores_sorted[:5][1:]

[(11, np.float64(0.21225446994394895)),
 (29, np.float64(0.1928675374858282)),
 (17, np.float64(0.07531468344381445)),
 (88, np.float64(0.07193947692894982))]

In [56]:
recommended_movie_indices = [i for i, _ in similarity_scores_sorted[:5][1:]]
recommended_movie_indices
recommended_movies = list(movies["title"].iloc[recommended_movie_indices])
for movie in recommended_movies:
    print(movie)

Quantum of Solace
Skyfall
Pirates of the Caribbean: On Stranger Tides
Big Hero 6